### ISSUE TITLE
Customizing Options

### ISSUE THREAD

**Issue by theRealJuliaMertens** [HiLabTufts/gailbot#14]
Hey HI Lab Team! 

A quick request - I'd like to be able to customize certain elements of the exported .cha file, if possible! 

1. the name of the file (so I don't overwrite by accident) 
2. The corpus name 
3. The location/ room layout / situation options
4. Characteristics of the speakers (e.g., gender) 
etc.

Grazie!
Julia

**Comment by theRealJuliaMertens** [comment]
After meeting today, there were some additional customization requests: 
1. default settings for "high", "medium" and "low" quality audio, which sets the confidence thresholds to various thresholds 
2. the option to override the default settings for confidence thresholds and timing

Thanks!!

**Comment by mumair01** [comment]
Added threshold and header customization options that can be activated by using command line flags with the initial command. If the flag is not invoked, default values are used instead. 
The next step is to specify the threshold values for high, medium, and low audio quality.

**Comment by mumair01** [comment]
@saulalbert Refer to J's comment for a bit more detail on the proposed update.
