### ISSUE TITLE
Example Audio / Video files that have been tested to work

### ISSUE THREAD

**Issue by joshkyh** [HiLabTufts/GailBot#2]
Hi,

Thank you for open sourcing the research work. I am looking to produce some Jeffersonian Transcripts using this program for my research. 

I have succeeded installing all software on MacOS Catalina. However, when using my own pairs of wav files or avi files, both of them failed to transcribe.

The avi files failed at the step of extracting wav files out of them. So I tried manually extracting the wav files and the wav files failed at the step after I select (8) start transcription. It reports "Initiating transcription process.." and then "Invalid selection. Please try again." At this point, I'm not sure whether its the audio is incompatible or my setup is wrong.

I think it would be helpful if we included a couple of video and audio files as working examples.

Thank you.

**Comment by saulalbert** [comment]
Hi Josh,

Thanks for getting in touch about this - and I'm glad you're planning on using GailBot.

@mumair01 is currently working on building out the next version of GailBot that will include a GUI and has been rebuilt from the ground up, so I'm sorry if the current version isn't working for you. 

But - good idea to suggest providing example files that we've tested. We can do that in the next version.

In the meantime - here is some sample output from a GailBot retranscription of the CallHome corpus on TalkBank (https://ca.talkbank.org/access/CallHome/eng.html):

https://www.dropbox.com/sh/rk4rjd9lwu4t791/AADNxhLVtnmMaGAMVhbpDxTOa?dl=0

That should include all the source files and GailBot's output files. If you aren't able to reproduce these results, let me know.

Best,

Saul.

**Comment by joshkyh** [comment]
Hi @saulalbert,

Thank you for sharing the zip over drop box. I would give it a shot!

Best Regards,
Joshua
